### PR TITLE
Reusable Alert presenting in UIKIT

### PR DESCRIPTION
**Pull request by randhirkumar65**

### CODE REVIEW

**Comment by randhirkumar65** [comment]
@vishalkevin11 Added common reusable Alert Presenting. Refer attached screenshot for more details

https://user-images.githubusercontent.com/16973595/196027377-f9f0f2ed-9200-4451-90bd-7405a6aad269.mp4

**Comment by vishalkevin11** [comment]
> @vishalkevin11 Added common reusable Alert Presenting. Refer attached screenshot for more details
> 
>  alert-presenting-uikit.mp4

@randhirkumar65 Awesome work here, Thanks for contributing. Could you please add the above GIF in the Readme file too? This helps developers understand quickly about this feature who clone the repo.

**Comment by randhirkumar65** [comment]
> > @vishalkevin11 Added common reusable Alert Presenting. Refer attached screenshot for more details
> > alert-presenting-uikit.mp4
> 
> @randhirkumar65 Awesome work here, Thanks for contributing. Could you please add the above GIF in the Readme file too? This helps developers understand quickly about this feature who clone the repo.
@vishalkevin11 Sure , updating it . Thanks for quick review

**Comment by randhirkumar65** [comment]
> > > @vishalkevin11 Added common reusable Alert Presenting. Refer attached screenshot for more details
> > > alert-presenting-uikit.mp4
> > 
> > 
> > @randhirkumar65 Awesome work here, Thanks for contributing. Could you please add the above GIF in the Readme file too? This helps developers understand quickly about this feature who clone the repo.
> > @vishalkevin11 Sure , updating it . Thanks for quick review

Hi @vishalkevin11 , Opened a PR to add gif to github assests repo, can you please approve this https://github.com/TeaTalkInternal/github_assets/pull/1

**Comment by vishalkevin11** [comment]
> 
@randhirkumar65  Thanks for making those changes. Merging in 👍

**Pull request merged**
